### ISSUE TITLE
Helm: Not able to generate keys. 

### ISSUE THREAD

**Issue by ashishxooa** [PegaSysEng/pantheon-kubernetes#7]
Hi team, 

I am trying to follow the link https://github.com/PegaSysEng/pantheon-kubernetes/tree/master/helm/private-network-ibft/pantheon to setup pantheon on K8s. However I am getting the below error in the very 1st step. Is there any pre-req to this? The file which is not present should be inside the container I suppose. If not can I get a link to this file, I couldn't find it inside the repo. Thanks

`➜  Pantheon docker run --rm --volume $PWD/ibftSetup/:/opt/pantheon/data pegasyseng/pantheon:develop operator generate-blockchain-config --config-file=/opt/pantheon/data/ibftConfigFile.json --to=/opt/pantheon/data/networkFiles --private-key-file-name=key

2019-09-04 11:35:42.019+00:00 | main | ERROR | OperatorSubCommand | An error occurred while trying to generate network configuration.
java.io.FileNotFoundException: /opt/pantheon/data/ibftConfigFile.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:112) ~[?:?]
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86) ~[?:?]
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184) ~[?:?]
	at java.net.URL.openStream(URL.java:1117) ~[?:?]
	at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:70) ~[guava-28.0-jre.jar:?]
	at com.google.common.io.ByteSource.read(ByteSource.java:285) ~[guava-28.0-jre.jar:?]
	at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:470) ~[guava-28.0-jre.jar:?]
	at com.google.common.io.Resources.toString(Resources.java:109) ~[guava-28.0-jre.jar:?]
	at tech.pegasys.pantheon.cli.subcommands.operator.OperatorSubCommand$GenerateNetworkConfigSubCommand.parseConfig(OperatorSubCommand.java:276) ~[pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at tech.pegasys.pantheon.cli.subcommands.operator.OperatorSubCommand$GenerateNetworkConfigSubCommand.generateBlockchainConfig(OperatorSubCommand.java:160) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at tech.pegasys.pantheon.cli.subcommands.operator.OperatorSubCommand$GenerateNetworkConfigSubCommand.run(OperatorSubCommand.java:145) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at picocli.CommandLine.execute(CommandLine.java:1160) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine.access$800(CommandLine.java:141) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) [picocli-3.9.6.jar:3.9.6]
	at tech.pegasys.pantheon.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:59) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at tech.pegasys.pantheon.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:29) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) [picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) [picocli-3.9.6.jar:3.9.6]
	at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:791) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:697) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]
	at tech.pegasys.pantheon.Pantheon.main(Pantheon.java:47) [pantheon-1.2.3-SNAPSHOT.jar:1.2.3-dev-6dbe1bc8]`

**Comment by EdJoJob** [comment]
Thanks for bringing this to our attention.  We have a fix for this in #8

**Comment by EdJoJob** [comment]
Please let us know if that change has fixed the issue you are seeing.

**Comment by ashishxooa** [comment]
@EdJoJob thanks, it's working now.

**Comment by EdJoJob** [comment]
Fixed in #8
